from pathlib import Path
import re
p=Path('index.html')
s=p.read_text()
s=re.sub(r'<title>.*?</title>','<title>LAME — Howie Lucas Pinball v13</title>',s,count=1)
# Add results styling
s=s.replace('</style>','.finalResults{margin-top:10px;text-align:left}.finalHero{text-align:center;background:#0a0d10;border:2px solid #f2b900;border-radius:12px;padding:10px;margin-bottom:8px}.finalHero b{color:#ffd532;font-size:22px}.finalGrid{display:grid;grid-template-columns:1fr 1fr;gap:8px}.finalCard{background:#080b0e;border:1px solid #36516a;border-radius:10px;padding:8px}.finalCard h4{margin:0 0 6px;color:#70d7ff;text-align:center}.finalRow{display:grid;grid-template-columns:24px 1fr auto;gap:5px;padding:4px 0;border-top:1px solid #26313a;font-size:11px;font-weight:900}.youRank{color:#ffd532;font-weight:1000}@media(max-width:460px){.finalGrid{grid-template-columns:1fr}}</style>',1)
# Solid black/white table art only
s=re.sub(r'function drawFittedGraphic\(\)\{.*?\}(?=\nfunction drawHowieRunning)', '''function drawFittedGraphic(){ctx.save();ctx.fillStyle=boxOpen===4?"#ffffff":"#000000";ctx.fillRect(0,0,W,WORLD_H);ctx.restore()}''', s, count=1, flags=re.S)
# Stick-figure Howie that stays visible whenever all 4 flaps are open
runner='''function drawHowieRunning(){if(boxOpen<4)return;const t=performance.now()/1000;const minY=cameraY+150,maxY=cameraY+VIEW_H-170;const x=300+Math.sin(t*1.6)*175;const y=clamp(cameraY+VIEW_H*.48+Math.cos(t*1.15)*125,minY,maxY);const dir=Math.cos(t*1.6)>=0?1:-1;const step=Math.sin(t*10);ctx.save();ctx.translate(x,y);ctx.scale(dir,1);ctx.lineCap="round";ctx.lineJoin="round";ctx.strokeStyle="#111";ctx.fillStyle="#7b4826";ctx.lineWidth=7;ctx.beginPath();ctx.arc(0,-58,19,0,Math.PI*2);ctx.fill();ctx.strokeStyle="#111";ctx.lineWidth=4;ctx.stroke();ctx.beginPath();ctx.moveTo(-16,-61);ctx.lineTo(-3,-61);ctx.moveTo(3,-61);ctx.lineTo(16,-61);ctx.moveTo(-3,-61);ctx.lineTo(3,-61);ctx.stroke();ctx.fillStyle="#111";ctx.beginPath();ctx.roundRect(-24,-38,48,64,10);ctx.fill();ctx.fillStyle="#fff";ctx.font="900 11px Arial";ctx.textAlign="center";ctx.fillText("HOWIE",0,-3);ctx.strokeStyle="#111";ctx.lineWidth=8;ctx.beginPath();ctx.moveTo(-18,-26);ctx.lineTo(-42,-6-step*10);ctx.moveTo(18,-26);ctx.lineTo(42,4+step*10);ctx.moveTo(-12,25);ctx.lineTo(-30,60+step*12);ctx.moveTo(12,25);ctx.lineTo(30,60-step*12);ctx.stroke();ctx.fillStyle="rgba(255,210,31,.96)";ctx.fillRect(-58,72,116,25);ctx.fillStyle="#111";ctx.font="900 13px Arial";ctx.fillText("HOWIE IS FREE!",0,90);ctx.restore()}'''
s=re.sub(r'function drawHowieRunning\(\)\{.*?\}(?=\nfunction drawWorld)',runner,s,count=1,flags=re.S)
# Remove dark image wash so the black/white states are obvious
s=re.sub(r'const grad=ctx\.createLinearGradient\(0,0,0,WORLD_H\);.*?ctx\.fillRect\(0,0,W,WORLD_H\);','',s,count=1,flags=re.S)
# End-game global comparison helpers
helpers='''function rankText(value,rows,field){const vals=rows.map(r=>Number(r[field]||0));const idx=vals.findIndex(v=>value>=v);if(idx>=0)return "#"+(idx+1)+" GLOBAL";return vals.length<5?"#"+(vals.length+1)+" GLOBAL":"OUTSIDE TOP 5"}function finalBoard(rows,field,isTime){return rows.slice(0,5).map((r,i)=>`<div class="finalRow"><span>#${i+1}</span><span>${escName(r.player_name)}</span><span>${isTime?formatTime(Number(r[field])||0):Number(r[field]||0).toLocaleString()}</span></div>`).join("")||'<div class="finalRow"><span>—</span><span>No results yet</span><span></span></div>'}function renderFinalResults(finalScore,finalOut){const scoreRank=rankText(finalScore,topScores,"score"),timeRank=rankText(finalOut,topOutTimes,"howie_out_ms");document.getElementById("finalScore").innerHTML=`<div class="finalResults"><div class="finalHero"><div>${escName(playerName)}</div><b>${finalScore.toLocaleString()} PTS</b><div class="youRank">${scoreRank}</div><div>Howie OUT: <b>${formatTime(finalOut)}</b> • <span class="youRank">${timeRank}</span></div><div style="margin-top:5px">ALL-TIME PLAYS: <b>${stats.plays.toLocaleString()}</b></div></div><div class="finalGrid"><div class="finalCard"><h4>🏆 GLOBAL TOP 5 SCORES</h4>${finalBoard(topScores,"score",false)}</div><div class="finalCard"><h4>⏱️ GLOBAL TOP 5 OUT TIMES</h4>${finalBoard(topOutTimes,"howie_out_ms",true)}</div></div></div>`}'''
s=s.replace('function loseBall(){',helpers+'\nasync function loseBall(){',1)
# Replace full loseBall body with async results flow
s=re.sub(r'async function loseBall\(\)\{.*?\}(?=function stuckBallReset)', '''async function loseBall(){boxOpen=0;updateFlaps();setStatus("BALL LOST — HOWIE IS BACK IN THE BOX");if(currentBall>=3){playing=false;if(outStartedAt){outAccumMs+=performance.now()-outStartedAt;outStartedAt=0}wasFullyOpen=false;const finalOut=outAccumMs;document.getElementById("finalScore").innerHTML="Saving your global results...";document.getElementById("gameOver").classList.remove("hide");await recordGameFinish(score,finalOut);renderFinalResults(score,finalOut)}else{currentBall++;resetBall();updateHud()}}''', s, count=1, flags=re.S)
p.write_text(s)
print('v13 applied')
