from pathlib import Path
p=Path('index.html')
s=p.read_text()

def rep(a,b):
    global s
    if a not in s:
        raise SystemExit('missing target: '+a[:120])
    s=s.replace(a,b,1)

rep('LAME — Howie Lucas Pinball v31','LAME — Howie Lucas Pinball v32')
rep('.panel button{width:100%;background:#f2b900;color:#111}', '.panel button{width:100%;background:#f2b900;color:#111}.panel #watchComputer{margin-top:9px;background:#1976d2;color:#fff;border:2px solid #77c7ff;box-shadow:0 0 16px #1976d255}')
rep('<button id="startBtn">START GAME</button>', '<button id="startBtn">START GAME</button><button id="watchComputer">🤖 WATCH COMPUTER PLAY</button>')
rep('let score=0,currentBall=1,level=1,playing=false,waiting=true,left=false,right=false,combo=1,lastHit=0,cameraY=400,inShooter=true,boxOpen=0,nextFlapScore=FLAP_GOAL,transitioning=false,won=false,drainCommitted=false;', 'let score=0,currentBall=1,level=1,playing=false,waiting=true,left=false,right=false,combo=1,lastHit=0,cameraY=400,inShooter=true,boxOpen=0,nextFlapScore=FLAP_GOAL,transitioning=false,won=false,drainCommitted=false,autoPlay=false,computerLaunchAt=0,computerFlipAt=0;')
rep('function resetBall(){drainCommitted=false;ball.x=535;ball.y=1165;ball.vx=ball.vy=0;waiting=true;inShooter=true;cameraY=400;combo=1;if(powerFill)powerFill.style.width="0%";if(powerPct)powerPct.textContent="0%";updateHud();setStatus("LEVEL "+level+" — HOLD LAUNCH")}', 'function resetBall(){drainCommitted=false;ball.x=535;ball.y=1165;ball.vx=ball.vy=0;waiting=true;inShooter=true;cameraY=400;combo=1;computerLaunchAt=autoPlay?performance.now()+850:0;if(powerFill)powerFill.style.width="0%";if(powerPct)powerPct.textContent="0%";updateHud();setStatus(autoPlay?"COMPUTER IS LINING UP THE LAUNCH...":"LEVEL "+level+" — HOLD LAUNCH")}')
rep('function draw(){ctx.clearRect(0,0,W,VIEW_H);ctx.save();ctx.translate(0,-cameraY);drawWorld();ctx.restore()}function loop(){physics();draw();if(boxOpen===4&&playing)outEl.textContent=fmt(outMs());requestAnimationFrame(loop)}function startGame(){initAudio();const n=(nicknameInput.value||playerName||"").trim().slice(0,18);if(!n){nicknameInput.focus();setStatus("Enter a nickname first");return}playerName=n;localStorage.setItem("lameNicknameV11",playerName);', 'function draw(){ctx.clearRect(0,0,W,VIEW_H);ctx.save();ctx.translate(0,-cameraY);drawWorld();ctx.restore()}function computerTap(side){const now=performance.now();if(side==="L"){left=true;flipperMotionUntil.L=now+190;setTimeout(()=>{if(autoPlay)left=false},125)}else{right=true;flipperMotionUntil.R=now+190;setTimeout(()=>{if(autoPlay)right=false},125)}}function computerControl(){if(!autoPlay||!playing||transitioning||won)return;const now=performance.now();if(waiting){if(computerLaunchAt&&now>=computerLaunchAt){computerLaunchAt=0;const p=.78+Math.random()*.22;setLaunchPower(p);launch(p);setStatus("🤖 COMPUTER LAUNCHED THE BALL")}return}if(inShooter||drainCommitted)return;if(ball.vy>0&&ball.y>900&&ball.y<1145&&now>=computerFlipAt){const predicted=ball.x+ball.vx*5.5;if(predicted<345)computerTap("L");if(predicted>255)computerTap("R");computerFlipAt=now+155;setStatus("🤖 COMPUTER IS PLAYING • LEVEL "+level+"/5")}}function loop(){computerControl();physics();draw();if(boxOpen===4&&playing)outEl.textContent=fmt(outMs());requestAnimationFrame(loop)}function startGame(){initAudio();const n=autoPlay?"Computer":(nicknameInput.value||playerName||"").trim().slice(0,18);if(!n){nicknameInput.focus();setStatus("Enter a nickname first");return}playerName=n;if(!autoPlay)localStorage.setItem("lameNicknameV11",playerName);')
rep('document.getElementById("startBtn").onclick=startGame;document.getElementById("againBtn").onclick=startGame;document.getElementById("restart").onclick=startGame;', 'document.getElementById("startBtn").onclick=()=>{autoPlay=false;startGame()};document.getElementById("watchComputer").onclick=()=>{autoPlay=true;nicknameInput.value="Computer";startGame()};document.getElementById("againBtn").onclick=()=>{if(!autoPlay)nicknameInput.value=localStorage.getItem("lameNicknameV11")||"";startGame()};document.getElementById("restart").onclick=()=>{autoPlay=false;nicknameInput.value=localStorage.getItem("lameNicknameV11")||"";startGame()};')
rep('nicknameInput.value=playerName;applyLayout();updateHud();loadStats();loop();', 'nicknameInput.value=playerName;applyLayout();updateHud();loadStats();loop();')
p.write_text(s)
print('v32 patched: computer demo mode added')
