from pathlib import Path
p=Path('index.html')
s=p.read_text()

def rep(a,b):
    global s
    if a not in s:
        raise SystemExit('missing target: '+a[:100])
    s=s.replace(a,b,1)

rep('LAME — Howie Lucas Pinball v29','LAME — Howie Lucas Pinball v30')
rep('.rankRow .rk{color:#70d7ff}.rankRow .nm{overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.rankRow .val{color:#ffd21f}', '.rankRow .rk{color:#70d7ff}.rankRow .nm{overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.rankRow .val{color:#ffd21f}.rankRow .stamp{grid-column:2/4;color:#8fa7b8;font-size:8px;font-weight:700;margin-top:-1px}')
rep('let outAccum=0,outStarted=0,wasOpen=false,howieHitAt=0,boxLit=false,flipperMotionUntil={L:0,R:0},audioCtx=null,sirenNodes=null;', 'let outAccum=0,outStarted=0,wasOpen=false,howieHitAt=0,howieFlashUntil=0,boxLit=false,flipperMotionUntil={L:0,R:0},audioCtx=null,jingleTimer=null;')
rep('function startSiren(){if(!audioCtx||sirenNodes)return;const o=audioCtx.createOscillator(),g=audioCtx.createGain(),l=audioCtx.createOscillator(),lg=audioCtx.createGain();o.type="sawtooth";o.frequency.value=620;l.type="sine";l.frequency.value=1.7;lg.gain.value=260;l.connect(lg).connect(o.frequency);g.gain.value=.03;o.connect(g).connect(audioCtx.destination);o.start();l.start();sirenNodes={o,g,l}}function stopSiren(){if(!sirenNodes)return;try{sirenNodes.o.stop();sirenNodes.l.stop()}catch(e){}sirenNodes=null}', 'function playHowieJingle(){if(!audioCtx)return;const notes=[523.25,659.25,783.99,659.25];notes.forEach((f,i)=>tone(f,.18,"sine",.035,35,i*.16));tone(1046.5,.24,"triangle",.025,-40,.62)}function startSiren(){if(!audioCtx||jingleTimer)return;playHowieJingle();jingleTimer=setInterval(playHowieJingle,1450)}function stopSiren(){if(jingleTimer){clearInterval(jingleTimer);jingleTimer=null}}')
rep('function renderRows(el,rows,type){if(!el)return;const arr=(rows||[]).slice(0,5);el.innerHTML=arr.length?arr.map((r,i)=>`<div class="rankRow"><span class="rk">#${i+1}</span><span class="nm">${esc(r.player_name||"PLAYER")}</span><span class="val">${type==="time"?fmt(Number(r.howie_out_ms)||0):(Number(r.score)||0).toLocaleString()}</span></div>`).join(""):`<div class="rankRow"><span class="rk">—</span><span class="nm">No record yet</span><span class="val">—</span></div>`}', 'function recordStamp(v){if(!v)return "";const d=new Date(v);if(Number.isNaN(d.getTime()))return "";return d.toLocaleString([], {month:"short",day:"numeric",year:"numeric",hour:"numeric",minute:"2-digit"})}function renderRows(el,rows,type){if(!el)return;const arr=(rows||[]).slice(0,5);el.innerHTML=arr.length?arr.map((r,i)=>`<div class="rankRow"><span class="rk">#${i+1}</span><span class="nm">${esc(r.player_name||"PLAYER")}</span><span class="val">${type==="time"?fmt(Number(r.howie_out_ms)||0):(Number(r.score)||0).toLocaleString()}</span><span class="stamp">${recordStamp(r.created_at)}</span></div>`).join(""):`<div class="rankRow"><span class="rk">—</span><span class="nm">No record yet</span><span class="val">—</span></div>`}')
rep('function getHowie(){const t=performance.now()/1000;return{x:300+Math.sin(t*1.7)*170,y:cameraY+450+Math.cos(t*1.1)*110}}function hitHowie(){if(boxOpen<4||inShooter)return;const h=getHowie(),dx=ball.x-h.x,dy=ball.y-h.y,d=Math.hypot(dx,dy),min=ball.r+38;if(d<min){const nx=dx/(d||1),ny=dy/(d||1),dot=ball.vx*nx+ball.vy*ny;if(dot<0){ball.vx-=2*dot*nx;ball.vy-=2*dot*ny}ball.x=h.x+nx*(min+2);ball.y=h.y+ny*(min+2);if(performance.now()-howieHitAt>180){howieHitAt=performance.now();sfxHit(2);addScore(750,h.x,h.y)}}}', 'function getHowie(){const t=performance.now()/1000;const vx=Math.cos(t*1.7)*289,vy=-Math.sin(t*1.1)*121;return{x:300+Math.sin(t*1.7)*170,y:cameraY+450+Math.cos(t*1.1)*110,vx,vy}}function hitHowie(){if(boxOpen<4||inShooter)return;const h=getHowie(),dx=ball.x-h.x,dy=ball.y-h.y,d=Math.hypot(dx,dy),min=ball.r+38;if(d<min){const nx=dx/(d||1),ny=dy/(d||1),dot=ball.vx*nx+ball.vy*ny;if(dot<0){ball.vx-=2.15*dot*nx;ball.vy-=2.15*dot*ny}const hm=Math.hypot(h.vx,h.vy)||1;ball.vx+=h.vx/hm*5.2;ball.vy+=h.vy/hm*5.2;ball.vx+=nx*2.4;ball.vy+=ny*2.4;ball.x=h.x+nx*(min+3);ball.y=h.y+ny*(min+3);capSpeed();howieFlashUntil=performance.now()+260;if(performance.now()-howieHitAt>150){howieHitAt=performance.now();sfxHit(2.4);tone(880,.08,"sine",.045,180);addScore(750,h.x,h.y);setStatus("HOWIE BUMPER! BALL KICKED WITH HIS MOMENTUM")}}}')
rep('function drawHowie(){if(boxOpen<4)return;const h=getHowie();ctx.save();ctx.translate(h.x,h.y);ctx.strokeStyle="#111";ctx.fillStyle="#7b4826";ctx.lineWidth=7;', 'function drawHowie(){if(boxOpen<4)return;const h=getHowie(),lit=performance.now()<howieFlashUntil;ctx.save();ctx.translate(h.x,h.y);if(lit){ctx.shadowBlur=38;ctx.shadowColor="#67c8ff";ctx.fillStyle="rgba(255,255,255,.28)";ctx.beginPath();ctx.arc(0,4,58,0,Math.PI*2);ctx.fill()}ctx.strokeStyle=lit?"#fff":"#111";ctx.fillStyle="#7b4826";ctx.lineWidth=lit?10:7;')
rep('if(boxOpen===4){const p=.08+.18*(.5+.5*Math.sin(performance.now()/90));ctx.fillStyle=`rgba(255,0,0,${p})`;ctx.fillRect(0,cameraY,W,VIEW_H);ctx.fillStyle="#ff1616";ctx.globalAlpha=.35+.65*(.5+.5*Math.sin(performance.now()/70));ctx.beginPath();ctx.arc(65,cameraY+70,23,0,Math.PI*2);ctx.fill();ctx.beginPath();ctx.arc(535,cameraY+70,23,0,Math.PI*2);ctx.fill();ctx.globalAlpha=1}', 'if(boxOpen===4){const pulse=.5+.5*Math.sin(performance.now()/95),p=.06+.16*pulse;ctx.fillStyle=pulse>.5?`rgba(60,165,255,${p})`:`rgba(255,255,255,${p*.8})`;ctx.fillRect(0,cameraY,W,VIEW_H);ctx.globalAlpha=.38+.62*pulse;ctx.fillStyle=pulse>.5?"#3fa9ff":"#fff";ctx.beginPath();ctx.arc(65,cameraY+70,23,0,Math.PI*2);ctx.fill();ctx.beginPath();ctx.arc(535,cameraY+70,23,0,Math.PI*2);ctx.fill();ctx.globalAlpha=1}')
p.write_text(s)
print('v30 patched')
# trigger update
