from pathlib import Path
p=Path('index.html')
s=p.read_text()
old='function levelSpeedFactor(){return Math.pow(2,Math.max(0,level-1))}function checkFlapMilestones(){if(levelTransitioning||gameWon)return;const goal=level*LEVEL_GOAL;if(score>=goal){if(level>=MAX_LEVEL){winGame()}else{advanceLevel()}}}function advanceLevel(){if(levelTransitioning||gameWon)return;levelTransitioning=true;playing=false;waiting=true;ball.vx=ball.vy=0;document.getElementById("levelDone").textContent="LEVEL "+level+" COMPLETE!";document.getElementById("levelNext").textContent="GET READY FOR LEVEL "+(level+1);document.getElementById("levelSpeed").textContent="BALL SPEED "+levelSpeedFactor()*2+"X";levelTransitionEl.classList.remove("hide");sfxBonus();setTimeout(()=>{level++;currentBall=1;combo=1;boxOpen=0;lamps.forEach(l=>l.on=false);updateFlaps();levelTransitionEl.classList.add("hide");playing=true;levelTransitioning=false;resetBall();updateHud();setStatus("LEVEL "+level+" — BALL SPEED "+levelSpeedFactor()+"X");sfxStart()},2300)}'
new='function levelSpeedFactor(){return [1,1.16,1.34,1.55,1.8][Math.max(0,Math.min(4,level-1))]}function checkFlapMilestones(){if(levelTransitioning||gameWon)return;while(boxOpen<4&&score>=nextFlapScore&&nextFlapScore<level*LEVEL_GOAL){boxOpen++;nextFlapScore+=FLAP_GOAL;updateFlaps();sfxFlap(boxOpen===4);spark(300,720,30);setStatus("BOX FLAP OPENED! "+boxOpen+"/4");if(boxOpen===4){outCelebrationUntil=performance.now()+5000;setStatus("HOWIE IS OUT THE BOX! DOUBLE POINTS!")}}if(score>=level*LEVEL_GOAL){if(level>=MAX_LEVEL)winGame();else advanceLevel()}}function advanceLevel(){if(levelTransitioning||gameWon)return;levelTransitioning=true;playing=false;waiting=true;ball.vx=ball.vy=0;boxOpen=0;updateFlaps();stopHowieSiren();document.getElementById("levelDone").textContent="CONGRATULATIONS!";document.getElementById("levelNext").textContent="YOU MADE IT TO LEVEL "+(level+1)+"!";document.getElementById("levelSpeed").textContent="NEW BOARD LOADING • SPEED "+Math.round([1,1.16,1.34,1.55,1.8][level]*100)+"%";levelTransitionEl.classList.remove("hide");sfxBonus();setTimeout(()=>{level++;currentBall=1;combo=1;boxOpen=0;nextFlapScore=(level-1)*LEVEL_GOAL+FLAP_GOAL;applyLevelLayout();lamps.forEach(l=>l.on=false);updateFlaps();levelTransitionEl.classList.add("hide");playing=true;levelTransitioning=false;resetBall();updateHud();setStatus("LEVEL "+level+" — NEW BOARD LOADED");sfxStart()},2700)}'
if old not in s:
    raise SystemExit('v24 progression not found')
s=s.replace(old,new,1)
s=s.replace('score=0;currentBall=1;combo=1;level=1;levelTransitioning=false;gameWon=false;playing=true;boxOpen=0;nextFlapScore=50000;','score=0;currentBall=1;combo=1;level=1;levelTransitioning=false;gameWon=false;playing=true;boxOpen=0;nextFlapScore=FLAP_GOAL;applyLevelLayout();',1)
s=s.replace('if(levelTextEl)levelTextEl.textContent=level+"/5";','if(levelTextEl)levelTextEl.textContent=level+"/5";const ci=document.getElementById("currentLevelIndicator"),ni=document.getElementById("nextLevelIndicator");if(ci)ci.textContent=level;if(ni)ni.textContent=level<MAX_LEVEL?level+1:"FINAL";',1)
p.write_text(s)
print('v25 progression applied')
