from pathlib import Path
p=Path('index.html')
s=p.read_text()
s=s.replace('LAME — Howie Lucas Pinball v26','LAME — Howie Lucas Pinball v27',1)
s=s.replace('let outAccum=0,outStarted=0,wasOpen=false,howieHitAt=0,flipperMotionUntil={L:0,R:0},audioCtx=null,sirenNodes=null;','let outAccum=0,outStarted=0,wasOpen=false,howieHitAt=0,boxHitFlash=0,boxHitAt=0,flipperMotionUntil={L:0,R:0},audioCtx=null,sirenNodes=null;',1)
box=Path('v27_box.txt').read_text()
s=s.replace('function getHowie(){',box+'function getHowie(){',1)
s=s.replace('posts.forEach(p=>circleHit(p,1.10,45));','posts.forEach(p=>circleHit(p,1.10,45));hitBoxBumper();',1)
s=s.replace('if(ball.y<135){inShooter=false;ball.y=135;ball.x=505;ball.vx=-5;ball.vy=1.4;sfxHit();addScore(250,490,120)}','if(ball.y<135){inShooter=false;ball.y=132;ball.x=498;ball.vx=-8.5;ball.vy=1.05;sfxHit(1.6);addScore(250,490,120);setStatus("LAUNCH LIP — BALL KICKED LEFT!")}',1)
lip=Path('v27_lipdraw.txt').read_text()
s=s.replace('ctx.strokeRect(500,130,72,1075);',lip,1)
boxdraw=Path('v27_boxdraw.txt').read_text()
s=s.replace('ctx.fillStyle="#6f3d18";ctx.fillRect(bx,by,bw,bh);ctx.strokeStyle="#e7ad63";ctx.lineWidth=4;ctx.strokeRect(bx,by,bw,bh);ctx.fillStyle="#111";ctx.font="900 42px Impact";ctx.fillText("LAME",300,790);',boxdraw,1)
p.write_text(s)
