(function(){
'use strict';
const V70={version:'81',dailyMode:false,startingDaily:false,daily:null,dailyTop:[],progress:null,paused:false,resumePlaying:false,lostBalls:0,breakoutMultiplier:1,breakoutShown:0,breakoutBoss:false,breakoutBossHp:1000000,breakoutBossMax:1000000,breakoutBossLastHit:0,bossBattleStarted:false,bossRetreatAt:0,bossRegenLast:0,howieBossHp:1000000,bossAttackLast:0,bossAttackUntil:0,howieStars:[],howieStarLast:0,boxLockGameOver:false,levelBossDefeated:false,bossSequenceRunning:false,mainDrainRegistered:false,bossHp:100,bossDefeated:false,bossLastHit:0,bossDamage:0,power:null,nextPowerAt:0,powerEnds:0,ballSave:false,maxCombo:1,bumperHits:0,replayFrames:[],replay:null,tutorialStep:0,tutorialActive:false,runSubmitted:false};
const SETTINGS_KEY='lameSettingsV70',XP_KEY='lameLocalXpV70',TUTORIAL_KEY='lameTutorialSeenV70';
const defaults={musicVolume:Math.round((window.musicVolume||.45)*100),effectsVolume:75,haptics:true,tutorial:true,graphics:'high'};
try{V70.settings=Object.assign({},defaults,JSON.parse(localStorage.getItem(SETTINGS_KEY)||'{}'))}catch(e){V70.settings={...defaults}}
V70.localXp=Math.max(0,Number(localStorage.getItem(XP_KEY)||0)||0);
const POWER_TYPES=[
 {id:'save',icon:'🛡️',name:'BALL SAVE',desc:'The next drain does not cost a ball',color:'#63e6ff'},
 {id:'triple',icon:'🔥',name:'TRIPLE POINTS',desc:'All points are tripled for 15 seconds',color:'#ff4e60'},
 {id:'magnet',icon:'🧲',name:'MAGNET BALL',desc:'The ball pulls toward high-value targets',color:'#b77cff'},
 {id:'giant',icon:'⚪',name:'GIANT BALL',desc:'A larger ball dominates the table for 12 seconds',color:'#ffffff'},
 {id:'mega',icon:'🌕',name:'5× MEGA BALL',desc:'The ball grows five times larger for 20 seconds',color:'#ffe15a'}
];
const UNLOCKS=[
 {xp:0,name:'Chrome Ball',desc:'Classic chrome finish'},
 {xp:500,name:'Blue Flame Trail',desc:'Bright blue momentum trail'},
 {xp:1200,name:'Purple Table Glow',desc:'Purple cabinet lighting'},
 {xp:2500,name:'Golden Ball',desc:'Gold ball highlights'},
 {xp:4500,name:'Howie Remix',desc:'Extra melody at combo x5'},
 {xp:7500,name:'Legend Trail',desc:'Rainbow champion trail'}
];
function saveSettings(){localStorage.setItem(SETTINGS_KEY,JSON.stringify(V70.settings))}
function resetComputerDeviceStats(){const marker='lameComputerStatsResetV77';if(localStorage.getItem(marker)==='1')return;try{const all=JSON.parse(localStorage.getItem('lamePersonalBestV65')||'{}')||{};for(const key of Object.keys(all))if(key.trim().toLowerCase()==='computer')delete all[key];localStorage.setItem('lamePersonalBestV65',JSON.stringify(all));localStorage.removeItem('lameComputerBrainV33');localStorage.setItem(marker,'1')}catch(e){}}
function xpLevel(xp){return Math.min(50,1+Math.floor(Math.sqrt(Math.max(0,xp)/250)))}
function xpFloor(lvl){return Math.pow(Math.max(0,lvl-1),2)*250}
function xpCeil(lvl){return Math.pow(lvl,2)*250}
function totalXp(){return Math.max(V70.localXp,Number(V70.progress&&V70.progress.xp)||0)}
function haptic(pattern){if(V70.settings.haptics&&navigator.vibrate)try{navigator.vibrate(pattern)}catch(e){}}
function esc70(v){return String(v==null?'':v).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function createUi(){
 const shell=document.querySelector('.shell')||document.body,controls=document.querySelector('.controls');
 const bar=document.createElement('div');bar.className='v70TopBar';bar.innerHTML='<div class="v70Xp"><div class="v70XpLine"><span id="v70XpLevel">LEVEL 1</span><span id="v70XpText">0 XP</span></div><div class="v70XpTrack"><div class="v70XpFill" id="v70XpFill"></div></div></div><button class="daily" id="dailyBtn">📅 DAILY</button><button class="pause" id="pauseBtn">⏸ SETTINGS</button>';
 (controls||shell.firstChild).insertAdjacentElement(controls?'afterend':'beforebegin',bar);
 if(controls){const total=document.createElement('div');total.id='v73TotalPoints';total.className='v73TotalPoints';total.innerHTML='<span>TOTAL POINTS</span><b id="v73TotalPointsValue">0</b>';controls.insertAdjacentElement('afterend',total)}
 const table=document.querySelector('.table');if(table){const badge=document.createElement('div');badge.id='dailyModeBadge';badge.className='dailyModeBadge';badge.hidden=true;badge.textContent='📅 DAILY CHALLENGE';table.appendChild(badge);const boss=document.createElement('div');boss.id='bossHud';boss.className='bossHud';boss.innerHTML='<div class="bossLine"><span>🔒 FINAL BOX LOCK</span><span id="bossHpText">100 / 100</span></div><div class="bossTrack"><div class="bossFill" id="bossFill"></div></div>';table.appendChild(boss);const pb=document.createElement('div');pb.id='powerBadge';pb.className='powerBadge';table.appendChild(pb);const replay=document.createElement('div');replay.id='instantReplay';replay.className='instantReplay';replay.innerHTML='<span id="replayLabel">INSTANT REPLAY</span>';table.appendChild(replay)}
 document.body.insertAdjacentHTML('beforeend','<div class="powerToast" id="powerToast"></div><div class="bossExplosion" id="bossExplosion"><div>💥</div><b>BOX BOSS DESTROYED!</b></div><div class="boxLockOver hide" id="boxLockOver"><b>GAME OVER</b><strong>3,000,000 POINTS<br>LOCKS YOU IN THE BOX</strong><span>TRY AGAIN</span></div><div class="tutorialCard hide" id="tutorialCard"><h3 id="tutorialTitle"></h3><p id="tutorialText"></p><div class="tutorialActions"><button class="v70Button" id="tutorialSkip">SKIP</button><button class="v70Button" id="tutorialNext">NEXT</button></div></div>');
 document.body.insertAdjacentHTML('beforeend',settingsMarkup()+dailyMarkup()+progressMarkup()+shareMarkup());
 document.getElementById('pauseBtn').onclick=()=>openSettings();document.getElementById('dailyBtn').onclick=()=>openDaily();
 document.getElementById('settingsClose').onclick=closeSettings;document.getElementById('resumeBtn').onclick=closeSettings;
 document.getElementById('dailyClose').onclick=()=>hideOverlay('dailyOverlay');document.getElementById('dailyPlay').onclick=startDaily;document.getElementById('startBtn').addEventListener('click',()=>{if(!V70.startingDaily){V70.dailyMode=false;document.getElementById('dailyModeBadge').hidden=true}},true);
 const howto=document.querySelector('.howto');if(howto)howto.insertAdjacentHTML('beforeend','<br><b>NEW LEVEL RULE:</b> Reach the point goal + free Howie, then destroy the moving 1,000,000 HP 🤬 Box Boss to advance.');
 document.getElementById('progressClose').onclick=()=>hideOverlay('progressOverlay');document.getElementById('shareClose').onclick=()=>hideOverlay('shareOverlay');
 document.getElementById('tutorialNext').onclick=nextTutorial;document.getElementById('tutorialSkip').onclick=endTutorial;
 bindSettingControls();updateXpUi();renderUnlocks();
}
function settingsMarkup(){return '<div class="v70Overlay hide" id="settingsOverlay"><div class="v70Panel"><h2>PAUSE & SETTINGS</h2><div class="v70SettingsGrid"><div class="v70Setting"><label>Music volume</label><input id="setMusic" type="range" min="0" max="100"></div><div class="v70Setting"><label>Sound effects</label><input id="setEffects" type="range" min="0" max="100"></div><div class="v70Setting"><label>Phone vibration</label><button class="v70Button v70Toggle" id="setHaptics"></button></div><div class="v70Setting"><label>Guided tutorial</label><button class="v70Button v70Toggle" id="setTutorial"></button></div><div class="v70Setting"><label>Graphics quality</label><select id="setGraphics"><option value="high">HIGH</option><option value="low">BATTERY SAVER</option></select></div></div><button class="v70Button" id="progressBtn">🏆 XP & UNLOCKS</button><button class="v70Button" id="resumeBtn">▶ RESUME GAME</button><button class="v70Button v70Close" id="settingsClose">CLOSE</button></div></div>'}
function dailyMarkup(){return '<div class="v70Overlay hide" id="dailyOverlay"><div class="v70Panel"><h2>DAILY HOWIE CHALLENGE</h2><div class="dailyHero"><div class="dailyDate" id="dailyDate">LOADING...</div><div class="dailyTitle" id="dailyTitle">TODAY\'S CHALLENGE</div><p class="dailyDesc" id="dailyDesc">Connecting to the global challenge...</p><button class="v70Button" id="dailyPlay">PLAY DAILY CHALLENGE</button></div><h3>🌎 TODAY\'S TOP 10</h3><div class="dailyRows" id="dailyRows"></div><button class="v70Button v70Close" id="dailyClose">CLOSE</button></div></div>'}
function progressMarkup(){return '<div class="v70Overlay hide" id="progressOverlay"><div class="v70Panel"><h2>HOWIE PLAYER LEVEL</h2><div class="dailyHero"><div class="dailyTitle" id="progressLevel">LEVEL 1</div><p class="dailyDesc" id="progressXp">0 XP</p></div><h3>UNLOCKABLE REWARDS</h3><div class="unlockGrid" id="unlockGrid"></div><button class="v70Button v70Close" id="progressClose">CLOSE</button></div></div>'}
function shareMarkup(){return '<div class="v70Overlay hide" id="shareOverlay"><div class="v70Panel"><h2>SHARE YOUR RUN</h2><canvas class="shareCardPreview" id="sharePreview" width="1200" height="630"></canvas><p>Your score card includes your nickname, score, level, XP and daily result.</p><button class="v70Button" id="nativeShareBtn">📲 SHARE RESULT CARD</button><button class="v70Button" id="facebookShareBtn">FACEBOOK LINK</button><button class="v70Button v70Close" id="shareClose">CLOSE</button></div></div>'}
function showOverlay(id){document.getElementById(id).classList.remove('hide')}
function hideOverlay(id){document.getElementById(id).classList.add('hide')}
function openSettings(){const startHidden=document.getElementById('startScreen').classList.contains('hide'),gameOverHidden=document.getElementById('gameOver').classList.contains('hide');V70.resumePlaying=startHidden&&gameOverHidden&&!won&&!transitioning;V70.paused=true;playing=false;document.body.classList.add('v70Paused');syncSettingControls();showOverlay('settingsOverlay')}
function closeSettings(){hideOverlay('settingsOverlay');document.body.classList.remove('v70Paused');V70.paused=false;if(V70.resumePlaying&&!won&&!transitioning){playing=true;if(musicEnabled)startHipHopBeat();setStatus(waiting?'GAME RESUMED — HOLD LAUNCH':'GAME RESUMED')}V70.resumePlaying=false}
function toggleButton(el,on){el.textContent=on?'ON':'OFF';el.classList.toggle('on',on);el.classList.toggle('off',!on)}
function syncSettingControls(){document.getElementById('setMusic').value=V70.settings.musicVolume;document.getElementById('setEffects').value=V70.settings.effectsVolume;document.getElementById('setGraphics').value=V70.settings.graphics;toggleButton(document.getElementById('setHaptics'),V70.settings.haptics);toggleButton(document.getElementById('setTutorial'),V70.settings.tutorial);document.body.classList.toggle('v70LowGraphics',V70.settings.graphics==='low')}
function bindSettingControls(){
 const m=document.getElementById('setMusic'),e=document.getElementById('setEffects');m.oninput=()=>{V70.settings.musicVolume=Number(m.value);musicVolume=V70.settings.musicVolume/100;musicEnabled=musicVolume>0;updateMusicControls();saveSettings()};e.oninput=()=>{V70.settings.effectsVolume=Number(e.value);saveSettings()};
 document.getElementById('setHaptics').onclick=()=>{V70.settings.haptics=!V70.settings.haptics;toggleButton(document.getElementById('setHaptics'),V70.settings.haptics);haptic(20);saveSettings()};
 document.getElementById('setTutorial').onclick=()=>{V70.settings.tutorial=!V70.settings.tutorial;toggleButton(document.getElementById('setTutorial'),V70.settings.tutorial);saveSettings()};
 document.getElementById('setGraphics').onchange=e=>{V70.settings.graphics=e.target.value;document.body.classList.toggle('v70LowGraphics',V70.settings.graphics==='low');saveSettings()};
 document.getElementById('progressBtn').onclick=()=>{hideOverlay('settingsOverlay');renderUnlocks();showOverlay('progressOverlay')};
}
function updateXpUi(){const xp=totalXp(),lvl=xpLevel(xp),lo=xpFloor(lvl),hi=xpCeil(lvl),pct=Math.max(0,Math.min(100,(xp-lo)/(hi-lo)*100));document.getElementById('v70XpLevel').textContent='PLAYER LV '+lvl;document.getElementById('v70XpText').textContent=xp.toLocaleString()+' XP';document.getElementById('v70XpFill').style.width=pct+'%';const a=document.getElementById('progressLevel'),b=document.getElementById('progressXp');if(a)a.textContent='PLAYER LEVEL '+lvl;if(b)b.textContent=xp.toLocaleString()+' XP • '+Math.max(0,hi-xp).toLocaleString()+' TO NEXT LEVEL';document.body.classList.toggle('v70PurpleUnlocked',xp>=1200)}
function renderUnlocks(){const xp=totalXp(),el=document.getElementById('unlockGrid');if(!el)return;el.innerHTML=UNLOCKS.map(u=>'<div class="unlockCard '+(xp>=u.xp?'unlocked':'')+'"><b>'+(xp>=u.xp?'✓ ':'🔒 ')+esc70(u.name)+'</b>'+esc70(u.desc)+'<br>'+u.xp.toLocaleString()+' XP</div>').join('');updateXpUi()}
async function loadV70Data(){try{const r=await fetch(GAME_API+'?playerId='+encodeURIComponent(playerId),{headers:{Authorization:'Bearer '+GAME_ANON_KEY,apikey:GAME_ANON_KEY}});if(!r.ok)throw new Error(String(r.status));const d=await r.json();V70.daily=d.dailyChallenge||null;V70.dailyTop=Array.isArray(d.dailyTop)?d.dailyTop:[];V70.progress=d.progress||null;renderDaily();renderUnlocks()}catch(e){document.getElementById('dailyDesc').textContent='Daily challenge is reconnecting. Regular play is still available.'}}
function renderDaily(){const d=V70.daily;if(!d)return;document.getElementById('dailyDate').textContent=d.date+' • SAME CHALLENGE FOR EVERYONE';document.getElementById('dailyTitle').textContent=d.title;document.getElementById('dailyDesc').textContent=d.description+' • Seed '+d.seed;const rows=document.getElementById('dailyRows');rows.innerHTML=V70.dailyTop.length?V70.dailyTop.map((r,i)=>'<div class="dailyRow"><b>#'+(i+1)+'</b><span>'+esc70(r.player_name||'PLAYER')+(r.completed?' ✓':'')+'</span><b>'+Number(r.score||0).toLocaleString()+'</b></div>').join(''):'<div class="dailyRow"><b>—</b><span>Be the first player today</span><b>—</b></div>'}
function openDaily(){renderDaily();showOverlay('dailyOverlay')}
function updateDailyBadge(){const badge=document.getElementById('dailyModeBadge');if(!badge||!V70.dailyMode||!V70.daily)return;badge.textContent='📅 '+V70.daily.title+' • '+Math.min(dailyObjectiveValue(),V70.daily.target).toLocaleString()+' / '+Number(V70.daily.target).toLocaleString()}
function startDaily(){if(!V70.daily)return;hideOverlay('dailyOverlay');V70.dailyMode=true;V70.startingDaily=true;const sel=document.getElementById('ballCountSelect');if(sel)sel.value='1';const badge=document.getElementById('dailyModeBadge');badge.hidden=false;updateDailyBadge();document.getElementById('startScreen').classList.remove('hide');setStatus('DAILY CHALLENGE: '+V70.daily.description);if((nicknameInput.value||'').trim())startGame();V70.startingDaily=false}
function dailyObjectiveValue(){if(!V70.daily)return 0;if(V70.daily.type==='bumper_hunt')return V70.bumperHits;if(V70.daily.type==='combo_king')return V70.maxCombo;if(V70.daily.type==='howie_time')return Math.floor(outMs());if(V70.daily.type==='boss_battle')return V70.bossDamage;return Math.floor(score)}
async function submitDaily(){if(!V70.dailyMode||V70.runSubmitted)return;V70.runSubmitted=true;try{const body={action:'daily-finish',playerId,playerName,score:Math.floor(score),howieOutMs:Math.floor(outMs()),levelReached:level,objectiveValue:dailyObjectiveValue(),bossDamage:V70.bossDamage};const r=await fetch(GAME_API,{method:'POST',headers:{Authorization:'Bearer '+GAME_ANON_KEY,apikey:GAME_ANON_KEY,'Content-Type':'application/json'},body:JSON.stringify(body)});if(!r.ok)throw new Error(String(r.status));const d=await r.json();V70.localXp+=Number(d.xpEarned)||0;localStorage.setItem(XP_KEY,String(V70.localXp));updateXpUi();showPowerToast(d.completed?'DAILY COMPLETE!':'DAILY RUN SAVED','+'+(d.xpEarned||0)+' XP');await loadV70Data()}catch(e){V70.runSubmitted=false}}
function bossPosition(){const t=performance.now()/1000;return{x:300+Math.sin(t*1.2)*105,y:430+Math.cos(t*.75)*28,r:58}}
function resetBoss(){V70.bossHp=100;V70.bossDefeated=false;V70.bossDamage=0;document.getElementById('bossHud').classList.remove('bossDefeated');updateBossHud()}
function updateBossHud(){const hud=document.getElementById('bossHud'),fill=document.getElementById('bossFill'),txt=document.getElementById('bossHpText');hud.classList.toggle('show',level===5&&!won);fill.style.width=Math.max(0,V70.bossHp)+'%';txt.textContent=V70.bossDefeated?'LOCK BROKEN':Math.max(0,V70.bossHp)+' / 100';hud.classList.toggle('bossDefeated',V70.bossDefeated)}
function collideBossFor(b){if(level!==5||V70.bossDefeated||!playing||waiting||(b===ball?inShooter:b.inShooter))return;const p=bossPosition(),dx=b.x-p.x,dy=b.y-p.y,d=Math.hypot(dx,dy),min=(b.r||13)+p.r;if(d>=min)return;const nx=dx/(d||1),ny=dy/(d||1),dot=b.vx*nx+b.vy*ny;if(dot<0){b.vx-=2.15*dot*nx;b.vy-=2.15*dot*ny}b.x=p.x+nx*(min+2);b.y=p.y+ny*(min+2);const now=performance.now();if(now-V70.bossLastHit<170)return;V70.bossLastHit=now;const damage=Math.max(4,Math.min(16,Math.round(Math.hypot(b.vx,b.vy)*1.2)));V70.bossHp=Math.max(0,V70.bossHp-damage);V70.bossDamage=Math.min(100,V70.bossDamage+damage);addScore(25000*damage,p.x,p.y);haptic([45,25,35]);sfxHit(2.5);updateBossHud();if(damage>=12||V70.bossHp<=0)startInstantReplay(V70.bossHp<=0?'FINAL LOCK BROKEN!':'BOSS HIT • '+damage+' DAMAGE');if(V70.bossHp<=0){V70.bossDefeated=true;V70.bossDamage=100;updateBossHud();showPowerToast('FINAL LOCK BROKEN','HOWIE IS FULLY FREE • +2,000,000');setTimeout(()=>{addScore(2000000,p.x,p.y);if(!won)V70.originalWinGame()},850)}}
function drawBoss(){if(level!==5||V70.bossDefeated)return;const p=bossPosition(),pulse=.5+.5*Math.sin(performance.now()/90);ctx.save();ctx.translate(p.x,p.y);ctx.shadowBlur=25+20*pulse;ctx.shadowColor='#ff233e';ctx.fillStyle='#180208';ctx.strokeStyle='#ff3b51';ctx.lineWidth=8;ctx.beginPath();ctx.arc(0,0,p.r,0,Math.PI*2);ctx.fill();ctx.stroke();ctx.rotate(performance.now()/500);for(let i=0;i<8;i++){ctx.rotate(Math.PI/4);ctx.fillStyle=i%2?'#ffb300':'#e3243d';ctx.fillRect(38,-7,27,14)}ctx.rotate(-performance.now()/500);ctx.fillStyle='#fff';ctx.font='900 25px Impact';ctx.textAlign='center';ctx.fillText('LOCK',0,7);ctx.fillStyle='#ffd21f';ctx.font='900 13px Arial';ctx.fillText(Math.max(0,V70.bossHp)+' HP',0,30);ctx.restore()}
function spawnPower(){if(!playing||waiting||transitioning||won||V70.power)return;const idx=V70.dailyMode&&V70.daily?Math.abs(V70.daily.seed+Math.floor(score/250000))%POWER_TYPES.length:Math.floor(Math.random()*POWER_TYPES.length);V70.power={...POWER_TYPES[idx],x:105+Math.random()*390,y:370+Math.random()*470,spawned:performance.now()};V70.nextPowerAt=performance.now()+26000+Math.random()*18000}
function checkPowerPickup(){if(!V70.power||!playing)return;const p=V70.power,d=Math.hypot(ball.x-p.x,ball.y-p.y);if(d>ball.r+28)return;activatePower(p);V70.power=null}
function activatePower(p){const now=performance.now();if(p.id==='save')V70.ballSave=true;else V70.powerEnds=now+(p.id==='mega'?20000:p.id==='triple'?15000:p.id==='giant'?12000:10000);V70.activePower=p.id;showPowerToast(p.icon+' '+p.name,p.desc);haptic([35,20,60]);sfxBonus();updatePowerBadge()}
function showPowerToast(title,desc){const el=document.getElementById('powerToast');el.innerHTML=esc70(title)+'<small>'+esc70(desc)+'</small>';el.classList.remove('show');void el.offsetWidth;el.classList.add('show')}
function updatePowerBadge(){const el=document.getElementById('powerBadge'),now=performance.now();if(V70.ballSave){el.textContent='🛡️ BALL SAVE READY';el.classList.add('show');return}if(V70.activePower&&now<V70.powerEnds){el.textContent=(POWER_TYPES.find(p=>p.id===V70.activePower)||{}).name+' '+Math.ceil((V70.powerEnds-now)/1000)+'s';el.classList.add('show');return}V70.activePower=null;el.classList.remove('show')}
function applyPowerPhysics(){const now=performance.now();if(V70.activePower&&now>=V70.powerEnds){V70.activePower=null;ball.r=13}if(V70.activePower==='mega')ball.r=65;else if(V70.activePower==='giant')ball.r=21;else if(ball.r!==13)ball.r=13;if(V70.activePower==='magnet'&&!waiting){let target=bumpers[0];for(const b of bumpers)if(Math.hypot(ball.x-b.x,ball.y-b.y)<Math.hypot(ball.x-target.x,ball.y-target.y))target=b;const dx=target.x-ball.x,dy=target.y-ball.y,d=Math.hypot(dx,dy)||1;ball.vx+=dx/d*.075;ball.vy+=dy/d*.075}updatePowerBadge()}
function drawPower(){if(!V70.power)return;const p=V70.power,pulse=.6+.4*Math.sin(performance.now()/110);ctx.save();ctx.translate(p.x,p.y);ctx.shadowBlur=18+18*pulse;ctx.shadowColor=p.color;ctx.fillStyle='#061018';ctx.strokeStyle=p.color;ctx.lineWidth=5;ctx.beginPath();ctx.arc(0,0,27,0,Math.PI*2);ctx.fill();ctx.stroke();ctx.font='26px Arial';ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText(p.icon,0,1);ctx.restore()}
function drawMegaCountdown(){if(V70.activePower!=='mega'||performance.now()>=V70.powerEnds)return;const left=Math.max(0,V70.powerEnds-performance.now()),pct=left/20000,w=126,x=Math.max(70,Math.min(530,ball.x)),y=ball.y-ball.r-32;ctx.save();ctx.textAlign='center';ctx.shadowBlur=16;ctx.shadowColor='#ffe15a';ctx.fillStyle='rgba(0,0,0,.78)';ctx.fillRect(x-w/2,y-18,w,31);ctx.fillStyle='#3b3210';ctx.fillRect(x-w/2+5,y+5,w-10,7);ctx.fillStyle='#ffe15a';ctx.fillRect(x-w/2+5,y+5,(w-10)*pct,7);ctx.fillStyle='#fff';ctx.font='900 16px Impact,Arial Black,Arial';ctx.fillText('5× MEGA • '+Math.ceil(left/1000)+'s',x,y);ctx.restore()}
function drawUnlockEffects(){const xp=totalXp();if(xp<500||waiting)return;const now=performance.now(),rainbow=xp>=7500,gold=xp>=2500;ctx.save();ctx.globalAlpha=.55;ctx.shadowBlur=20;ctx.shadowColor=rainbow?'hsl('+(now/8%360)+' 100% 60%)':gold?'#ffd21f':'#42c8ff';ctx.strokeStyle=ctx.shadowColor;ctx.lineWidth=3;ctx.beginPath();ctx.arc(ball.x,ball.y,ball.r+8+Math.sin(now/90)*3,0,Math.PI*2);ctx.stroke();for(let i=0;i<5;i++){const a=now/260+i*Math.PI*2/5,r=ball.r+13;ctx.fillStyle=rainbow?'hsl('+((now/5+i*55)%360)+' 100% 65%)':gold?'#ffd21f':'#61ddff';ctx.beginPath();ctx.arc(ball.x+Math.cos(a)*r,ball.y+Math.sin(a)*r,2.5,0,Math.PI*2);ctx.fill()}ctx.restore()}
function drawHowieFireworks(){if(boxOpen!==4||V70.settings.graphics==='low')return;const now=performance.now(),colors=['#ffd21f','#69e6ff','#ff4775','#8cff72','#ffffff'];ctx.save();ctx.globalCompositeOperation='lighter';for(let burst=0;burst<4;burst++){const cycle=(now/1450+burst*.23)%1,life=1-cycle,cx=95+burst*135,cy=cameraY+125+(burst%2)*95;for(let ray=0;ray<12;ray++){const a=ray*Math.PI/6+burst*.4,dist=cycle*88;ctx.globalAlpha=Math.max(0,life*.9);ctx.fillStyle=colors[(ray+burst)%colors.length];ctx.shadowBlur=12;ctx.shadowColor=ctx.fillStyle;ctx.beginPath();ctx.arc(cx+Math.cos(a)*dist,cy+Math.sin(a)*dist,2.5+life*2,0,Math.PI*2);ctx.fill()}}ctx.restore()}
function breakoutRemaining(){if(boxOpen>=4)return 0;const step=FLAP_GOAL*V70.breakoutMultiplier;return Math.max(0,nextFlapScore+(3-boxOpen)*step-score)}
function levelObjectivesMet(){return score>=level*LEVEL_GOAL&&boxOpen===4}
function activateLevelBoss(){if(V70.breakoutBoss||V70.levelBossDefeated||!levelObjectivesMet()||transitioning||won)return;const resumed=V70.bossBattleStarted;V70.bossBattleStarted=true;V70.breakoutBoss=true;V70.howieBossHp=1000000;V70.bossRetreatAt=0;V70.bossRegenLast=0;if(!resumed){V70.breakoutBossHp=1000000;V70.breakoutBossMax=1000000}showPowerToast(resumed?'🤬 BOSS FIGHT RESUMED':'🤬 LEVEL '+level+' BOX BOSS',resumed?'HOWIE RESTORED TO 100% • BOSS HP '+V70.breakoutBossHp.toLocaleString():'1,000,000 HP • DESTROY HIM TO ADVANCE');setStatus('HOWIE 1,000,000 HP • ONLY THE BOX BOSS CAN HURT HIM!');haptic([45,25,70])}
function finishLevelBossSequence(){if(V70.bossSequenceRunning||!V70.levelBossDefeated||!levelObjectivesMet())return;V70.bossSequenceRunning=true;playing=false;const fx=document.getElementById('bossExplosion');fx.classList.add('show');setTimeout(()=>{fx.classList.remove('show');V70.bossSequenceRunning=false;if(level===MAX_LEVEL){V70.bossDefeated=true;V70.bossDamage=100;V70.originalWinGame()}else advanceLevel()},1450)}
function destroyBreakoutBoss(){if(!V70.breakoutBoss)return;V70.breakoutBoss=false;V70.breakoutBossHp=0;V70.levelBossDefeated=true;V70.howieStars=[];V70.bossRetreatAt=0;V70.bossRegenLast=0;setStatus('🤬 BOX BOSS DESTROYED!');haptic([70,30,90,30,120]);sfxBonus();finishLevelBossSequence()}
function retreatBossWithHowie(){if(!V70.bossBattleStarted||V70.levelBossDefeated)return;V70.breakoutBoss=false;V70.bossRetreatAt=performance.now();V70.bossRegenLast=V70.bossRetreatAt;boxOpen=0;nextFlapScore=score+FLAP_GOAL*V70.breakoutMultiplier;updateFlaps();setStatus('HOWIE HP EMPTY • BACK IN THE BOX • BOSS IS RECHARGING!');showPowerToast('HOWIE IS BACK IN THE BOX','BOSS HEALTH REGENERATES UNTIL HOWIE GETS OUT')}
function regenerateRetreatedBoss(){if(!V70.bossBattleStarted||V70.breakoutBoss||V70.levelBossDefeated||!V70.bossRegenLast)return;const now=performance.now(),dt=Math.min(250,now-V70.bossRegenLast);V70.bossRegenLast=now;V70.breakoutBossHp=Math.min(1000000,V70.breakoutBossHp+dt*40)}
function syncBreakoutBoss(){regenerateRetreatedBoss();if(levelObjectivesMet())activateLevelBoss();if(V70.levelBossDefeated&&levelObjectivesMet())finishLevelBossSequence()}
function drawBreakoutPoints(){if(boxOpen>=4)return;const remaining=breakoutRemaining(),d=remaining-V70.breakoutShown;V70.breakoutShown=Math.abs(d)<1?remaining:V70.breakoutShown+d*(Math.abs(d)>1000000?.055:Math.abs(d)>250000?.075:.12);const pulse=.5+.5*Math.sin(performance.now()/105);ctx.save();ctx.globalAlpha=.72+.28*pulse;ctx.textAlign='center';ctx.shadowBlur=18+18*pulse;ctx.shadowColor=pulse>.5?'#ffffff':'#36bfff';ctx.fillStyle=pulse>.5?'#ffffff':'#69dfff';ctx.font='900 30px Impact,Arial Black,Arial';ctx.fillText(Math.floor(V70.breakoutShown).toLocaleString()+' PTS NEEDED',300,660);ctx.font='900 17px Impact,Arial Black,Arial';ctx.fillText('TO GET HOWIE OUT',300,684);ctx.restore()}
function breakoutBossPosition(){const t=performance.now()/1000;return{x:300+Math.sin(t*1.08)*174,y:430+Math.sin(t*.73+1.4)*135,r:76}}
function drawBreakoutBoss(){syncBreakoutBoss();if(!V70.breakoutBoss)return;const p=breakoutBossPosition(),pct=Math.max(0,Math.min(1,V70.breakoutBossHp/1000000)),pulse=.5+.5*Math.sin(performance.now()/80);ctx.save();ctx.translate(p.x,p.y);ctx.textAlign='center';ctx.shadowBlur=30+22*pulse;ctx.shadowColor=pulse>.5?'#ff304c':'#ffffff';ctx.font='120px Arial';ctx.fillText('🤬',0,38);ctx.shadowBlur=18;ctx.fillStyle='#fff';ctx.font='900 18px Impact,Arial Black,Arial';ctx.fillText('LEVEL '+level+' BOX BOSS',0,72);ctx.fillStyle='rgba(0,0,0,.86)';ctx.fillRect(-116,84,232,43);ctx.fillStyle='#172635';ctx.fillRect(-110,90,220,13);ctx.fillStyle=pct>.5?'#51d9ff':'#ff304c';ctx.fillRect(-110,90,220*pct,13);ctx.fillStyle='#fff';ctx.font='900 16px Impact,Arial Black,Arial';ctx.fillText(Math.ceil(V70.breakoutBossHp).toLocaleString()+' HP',0,122);ctx.restore()}
function updateBossAttack(){if(!V70.breakoutBoss||!V70.bossBattleStarted||V70.levelBossDefeated||boxOpen!==4||!playing||waiting||transitioning)return;const now=performance.now(),p=breakoutBossPosition(),h=getHowie(),distance=Math.hypot(h.x-p.x,h.y-p.y);if(distance>285||now-V70.bossAttackLast<850)return;V70.bossAttackLast=now;V70.bossAttackUntil=now+260;V70.howieBossHp=Math.max(0,V70.howieBossHp-50000);haptic([25,18,38]);sfxHit(1.9);setStatus('🤬 BOSS HIT HOWIE • '+V70.howieBossHp.toLocaleString()+' HOWIE HP LEFT');if(V70.howieBossHp<=0)retreatBossWithHowie()}
function drawBossAttackAndHowieHealth(){if(!V70.bossBattleStarted||V70.levelBossDefeated||!V70.breakoutBoss||boxOpen!==4)return;const now=performance.now(),p=breakoutBossPosition(),h=getHowie(),pct=Math.max(0,Math.min(1,V70.howieBossHp/1000000));ctx.save();if(now<V70.bossAttackUntil){ctx.globalCompositeOperation='lighter';ctx.strokeStyle='#ff304c';ctx.shadowColor='#ff304c';ctx.shadowBlur=28;ctx.lineWidth=9;ctx.beginPath();ctx.moveTo(p.x,p.y);ctx.lineTo(h.x,h.y);ctx.stroke();ctx.strokeStyle='#fff';ctx.lineWidth=3;ctx.stroke()}ctx.textAlign='center';ctx.fillStyle='rgba(0,0,0,.86)';ctx.fillRect(h.x-105,h.y-112,210,52);ctx.strokeStyle='#ffffff';ctx.lineWidth=3;ctx.strokeRect(h.x-105,h.y-112,210,52);ctx.fillStyle='#32121a';ctx.fillRect(h.x-96,h.y-82,192,11);ctx.fillStyle=pct>.35?'#51d9ff':'#ff304c';ctx.fillRect(h.x-96,h.y-82,192*pct,11);ctx.fillStyle='#fff';ctx.font='900 15px Impact,Arial Black,Arial';ctx.fillText('HOWIE • '+Math.ceil(V70.howieBossHp).toLocaleString()+' HP',h.x,h.y-91);ctx.restore()}
function drawBossCornerHud(){if(!V70.bossBattleStarted||V70.levelBossDefeated)return;const charging=!V70.breakoutBoss,pct=Math.max(0,Math.min(1,V70.breakoutBossHp/1000000)),x=W-218,y=charging?112:18,pulse=.45+.55*Math.abs(Math.sin(performance.now()/145));ctx.save();ctx.fillStyle='rgba(0,0,0,.86)';ctx.strokeStyle=charging?'#ffd21f':'#ff304c';ctx.lineWidth=3;ctx.fillRect(x,y,200,charging?91:68);ctx.strokeRect(x,y,200,charging?91:68);ctx.fillStyle='#fff';ctx.font='900 14px Impact,Arial Black,Arial';ctx.textAlign='center';ctx.fillText(charging?'🤬 BOSS HEALTH':'🤬 BOSS HEALTH',x+100,y+20);ctx.fillStyle='#35121a';ctx.fillRect(x+10,y+30,180,12);ctx.fillStyle=pct>.5?'#ff304c':'#ff7b37';ctx.fillRect(x+10,y+30,180*pct,12);ctx.fillStyle='#fff';ctx.font='900 14px Impact,Arial Black,Arial';ctx.fillText(Math.ceil(V70.breakoutBossHp).toLocaleString()+' / 1,000,000',x+100,y+59);if(charging){ctx.globalAlpha=pulse;ctx.shadowBlur=22;ctx.shadowColor='#ffd21f';ctx.fillStyle='#fff36a';ctx.font='900 18px Impact,Arial Black,Arial';ctx.fillText('⚡ CHARGING ⚡',x+100,y+82)}ctx.restore()}
function howieStarAttackReady(){return V70.breakoutBoss&&V70.bossBattleStarted&&!V70.levelBossDefeated&&boxOpen===4&&playing&&!waiting&&!transitioning}
function throwHowieStar(){const now=performance.now();if(!howieStarAttackReady()||now-V70.howieStarLast<320)return false;V70.howieStarLast=now;const h=getHowie();V70.howieStars.push({x:h.x,y:h.y,start:now,spin:Math.random()*6.28});if(V70.howieStars.length>12)V70.howieStars.shift();tone(1180,.055,'triangle',.035,420);haptic(18);setStatus('⭐ HOWIE THREW A STAR AT THE BOSS!');return true}
function updateHowieStars(){const now=performance.now();for(let i=V70.howieStars.length-1;i>=0;i--){const s=V70.howieStars[i];if(!V70.breakoutBoss||V70.levelBossDefeated){V70.howieStars.splice(i,1);continue}const p=breakoutBossPosition(),dx=p.x-s.x,dy=p.y-s.y,d=Math.hypot(dx,dy)||1,step=Math.min(d,8.5);s.x+=dx/d*step;s.y+=dy/d*step;s.spin+=.25;if(d<86||now-s.start>1800){V70.howieStars.splice(i,1);V70.breakoutBossHp=Math.max(0,V70.breakoutBossHp-25000);showPointPopup(25000,p.x,p.y);score+=25000;updateHud();sfxHit(1.8);setStatus('⭐ STAR HIT! +25,000 • BOSS '+V70.breakoutBossHp.toLocaleString()+' HP');if(V70.breakoutBossHp<=0)destroyBreakoutBoss()}}}
function drawHowieStars(){ctx.save();ctx.textAlign='center';ctx.textBaseline='middle';ctx.font='42px Arial';for(const s of V70.howieStars){ctx.save();ctx.translate(s.x,s.y);ctx.rotate(s.spin);ctx.shadowBlur=24;ctx.shadowColor='#fff36a';ctx.fillText('⭐',0,0);ctx.restore()}ctx.restore()}
function updateStarLaunchButton(){const b=document.getElementById('launchBtn');if(!b)return;const wasActive=b.classList.contains('howieStarAttack'),active=howieStarAttackReady();b.classList.toggle('howieStarAttack',active);if(active){b.innerHTML='⭐<br>THROW STAR';b.setAttribute('aria-label','Howie throw star at boss')}else{b.removeAttribute('aria-label');if(wasActive)b.innerHTML=inShooter?'HOLD<br>LAUNCH':extraBallsQueued>0?'LAUNCH<br>NEXT BALL':'MULTIBALL<br>ACTIVE'}}
function ballStuckOnLaunchPad(){return playing&&!waiting&&!transitioning&&!won&&!launchRailActive&&ball.x>490&&ball.y>930&&Math.hypot(ball.vx,ball.vy)<2.4}
function updateLaunchPadRescue(){if(howieStarAttackReady())return;const b=document.getElementById('launchBtn');if(!b)return;const wasRescue=b.classList.contains('launchRescue');if(ballStuckOnLaunchPad()){b.classList.add('launchRescue');b.innerHTML='🚀<br>RE-LAUNCH'}else{b.classList.remove('launchRescue');if(wasRescue)b.innerHTML=inShooter?'HOLD<br>LAUNCH':extraBallsQueued>0?'LAUNCH<br>NEXT BALL':'MULTIBALL<br>ACTIVE'}}
async function triggerBoxLockGameOver(){if(V70.boxLockGameOver||boxOpen===4||breakoutRemaining()<3000000)return;V70.boxLockGameOver=true;playing=false;waiting=true;V70.breakoutBoss=false;V70.howieStars=[];stopHipHopBeat();const over=document.getElementById('boxLockOver');over.classList.remove('hide');haptic([100,50,140,50,220]);setTimeout(async()=>{over.classList.add('hide');await finishRecord();renderGameOver();const result=document.getElementById('finalScore');if(result)result.insertAdjacentHTML('afterbegin','<div class="boxLockResult">🔒 3,000,000-POINT BOX LOCK</div>');document.getElementById('gameOver').classList.remove('hide')},2600)}
function collideBreakoutBossFor(b){syncBreakoutBoss();if(!V70.breakoutBoss||!playing||waiting||(b===ball?inShooter:b.inShooter))return;const p=breakoutBossPosition(),dx=b.x-p.x,dy=b.y-p.y,d=Math.hypot(dx,dy),min=(b.r||13)+p.r;if(d>=min)return;const nx=dx/(d||1),ny=dy/(d||1),dot=b.vx*nx+b.vy*ny;if(dot<0){b.vx-=2.2*dot*nx;b.vy-=2.2*dot*ny}b.x=p.x+nx*(min+2);b.y=p.y+ny*(min+2);const now=performance.now();if(now-V70.breakoutBossLastHit<150)return;V70.breakoutBossLastHit=now;V70.breakoutBossHp=Math.max(0,V70.breakoutBossHp-40000);score+=40000;showPointPopup(40000,p.x,p.y);updateHud();haptic([38,18,48]);sfxHit(2.4);setStatus('🤬 BOX BOSS HIT! +40,000 • '+V70.breakoutBossHp.toLocaleString()+' HP LEFT');if(V70.breakoutBossHp<=0)destroyBreakoutBoss()}
function drawLargeHowieCounter(){if(boxOpen!==4)return;const h=getHowie();ctx.save();ctx.textAlign='center';ctx.shadowBlur=24;ctx.shadowColor='#ffd21f';ctx.fillStyle='#fff';ctx.font='900 18px Impact,Arial Black,Arial';ctx.fillText('HOWIE OUT POINTS',h.x,h.y+158);ctx.fillStyle='#ffd21f';ctx.font='900 38px Impact,Arial Black,Arial';ctx.fillText(Math.floor(howieOutPointsShown).toLocaleString(),h.x,h.y+196);ctx.restore()}
function updateBreakoutLabel(){const el=document.querySelector('.boxTitle span:last-child');if(el)el.textContent=(FLAP_GOAL*V70.breakoutMultiplier).toLocaleString()+' PTS = OPEN 1 FLAP • '+V70.breakoutMultiplier+'× COST'}
function registerBallLoss(){V70.lostBalls++;V70.breakoutMultiplier=V70.lostBalls+1;const battle=V70.bossBattleStarted&&!V70.levelBossDefeated;boxOpen=0;nextFlapScore=score+FLAP_GOAL*V70.breakoutMultiplier;if(battle){V70.breakoutBoss=false;V70.bossRetreatAt=performance.now();V70.bossRegenLast=V70.bossRetreatAt}updateFlaps();updateBreakoutLabel();setStatus('BALL LOST • HOWIE IS BACK IN THE BOX • BREAKOUT COST '+V70.breakoutMultiplier+'×');showPowerToast('HOWIE IS BACK IN THE BOX',battle?'BOSS RETREATED • HEALTH REGENERATING':V70.breakoutMultiplier+'× POINTS NEEDED FOR ALL 4 FLAPS')}
function captureReplayFrame(){if(V70.replay||!playing||waiting)return;V70.replayFrames.push({x:ball.x,y:ball.y,cameraY,t:performance.now()});if(V70.replayFrames.length>75)V70.replayFrames.shift()}
function startInstantReplay(label){if(V70.replay||V70.replayFrames.length<18||transitioning||won)return;const was=playing;playing=false;V70.replay={label,frames:V70.replayFrames.slice(-55),start:performance.now(),was};document.getElementById('replayLabel').textContent='⏪ '+label;document.getElementById('instantReplay').classList.add('show');setTimeout(()=>{document.getElementById('instantReplay').classList.remove('show');const r=V70.replay;V70.replay=null;if(r&&r.was&&!V70.paused&&!won&&!transitioning)playing=true},1450)}
function drawReplayGhost(){if(!V70.replay)return;const r=V70.replay,p=Math.min(1,(performance.now()-r.start)/1300),i=Math.min(r.frames.length-1,Math.floor(p*r.frames.length)),f=r.frames[i];ctx.save();ctx.globalAlpha=.75;ctx.shadowBlur=28;ctx.shadowColor='#ffd21f';ctx.fillStyle='#fff';ctx.beginPath();ctx.arc(f.x,f.y-f.cameraY,18,0,Math.PI*2);ctx.fill();ctx.restore()}
const tutorialSteps=[
 {title:'LAUNCH THE BALL',text:'Hold LAUNCH to build momentum, then release. You can relaunch any ball stuck in the launch lane.',target:'#launchBtn'},
 {title:'CONTROL THE FLIPPERS',text:'Use LEFT and RIGHT to keep the ball alive. Keyboard players can use A/D or the arrow keys.',target:'.controls'},
 {title:'FREE HOWIE',text:'Score points to open all four box flaps. When Howie gets out, every point is doubled.',target:'.boxStatus'},
 {title:'GRAB POWER-UPS',text:'Hit glowing power-up icons for Ball Save, Triple Points, Magnet Ball, Giant Ball or the 20-second 5× Mega Ball.',target:'.table'},
 {title:'CLIMB AND SHARE',text:'Earn XP, unlock visual rewards, play the Daily Challenge and share your result card.',target:'.v70TopBar'}
];
function startTutorial(){if(!V70.settings.tutorial||localStorage.getItem(TUTORIAL_KEY)==='1')return;V70.tutorialActive=true;V70.tutorialStep=0;showTutorialStep()}
function clearTutorialTarget(){document.querySelectorAll('.tutorialPulse').forEach(e=>e.classList.remove('tutorialPulse'))}
function showTutorialStep(){const s=tutorialSteps[V70.tutorialStep],card=document.getElementById('tutorialCard');clearTutorialTarget();document.getElementById('tutorialTitle').textContent=(V70.tutorialStep+1)+' / '+tutorialSteps.length+' • '+s.title;document.getElementById('tutorialText').textContent=s.text;document.getElementById('tutorialNext').textContent=V70.tutorialStep===tutorialSteps.length-1?'FINISH':'NEXT';card.classList.remove('hide');document.querySelector(s.target)?.classList.add('tutorialPulse')}
function nextTutorial(){if(++V70.tutorialStep>=tutorialSteps.length)endTutorial();else showTutorialStep()}
function endTutorial(){clearTutorialTarget();document.getElementById('tutorialCard').classList.add('hide');V70.tutorialActive=false;localStorage.setItem(TUTORIAL_KEY,'1')}
function drawShareCard(){const c=document.getElementById('sharePreview'),g=c.getContext('2d'),xp=totalXp();const grad=g.createLinearGradient(0,0,1200,630);grad.addColorStop(0,'#05070a');grad.addColorStop(.55,'#14142c');grad.addColorStop(1,'#501025');g.fillStyle=grad;g.fillRect(0,0,1200,630);g.strokeStyle='#ffd21f';g.lineWidth=16;g.strokeRect(18,18,1164,594);g.fillStyle='#ffd21f';g.font='900 74px Impact';g.fillText('LAME PINBALL',65,105);g.fillStyle='#fff';g.font='900 40px Arial';g.fillText((playerName||'PLAYER').toUpperCase(),70,180);g.fillStyle='#ff476c';g.font='900 105px Impact';g.fillText(Math.floor(score).toLocaleString(),65,310);g.fillStyle='#fff';g.font='900 28px Arial';g.fillText('POINTS  •  LEVEL '+level+'/5  •  '+fmt(outMs())+' HOWIE-OUT',70,360);g.fillStyle='#71e6ff';g.font='900 31px Arial';g.fillText('PLAYER LEVEL '+xpLevel(xp)+'  •  '+xp.toLocaleString()+' XP',70,420);if(V70.dailyMode&&V70.daily){g.fillStyle='#d8b4fe';g.fillText('DAILY: '+V70.daily.title+'  •  '+V70.daily.description,70,475)}g.fillStyle='#fff';g.font='700 23px Arial';g.fillText('Can you beat Howie?  tragicc357.github.io/LAME-PINBALL-/',70,555);return c}
async function shareResultCard(){drawShareCard();showOverlay('shareOverlay')}
async function nativeShareCard(){const c=drawShareCard();c.toBlob(async blob=>{if(!blob)return;const file=new File([blob],'lame-pinball-score.png',{type:'image/png'});const text=(playerName||'I')+' scored '+Math.floor(score).toLocaleString()+' on LAME Pinball!';try{if(navigator.canShare&&navigator.canShare({files:[file]}))await navigator.share({title:'LAME Pinball Score',text,files:[file],url:'https://tragicc357.github.io/LAME-PINBALL-/'});else{const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=file.name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}}catch(e){}},'image/png')}
function facebookShare(){const url='https://tragicc357.github.io/LAME-PINBALL-/?v=70',text=(playerName||'I')+' scored '+Math.floor(score).toLocaleString()+' points and reached Level '+level+'/5 on LAME Pinball!';window.open('https://www.facebook.com/sharer/sharer.php?u='+encodeURIComponent(url)+'&quote='+encodeURIComponent(text),'facebook-share','width=680,height=760')}
function installHooks(){
 openFlapsAndLevels=function(){const step=FLAP_GOAL*V70.breakoutMultiplier;while(boxOpen<4&&score>=nextFlapScore){boxOpen++;nextFlapScore+=step;updateFlaps();sfxBonus();celebrationUntil=performance.now()+1100;setStatus('BOX FLAP OPENED! '+boxOpen+'/4 • '+V70.breakoutMultiplier+'× BREAKOUT COST');if(boxOpen===4){howieOutPoints=0;howieOutPointsShown=0;setStatus('HOWIE IS OUT THE BOX!');showPowerToast('HOWIE IS OUT!','DEFAULT OBJECTIVE COMPLETE • BOSS BATTLE NEXT')}}if(score>=level*LEVEL_GOAL&&boxOpen<4)setStatus('POINT GOAL MET • FREE HOWIE TO SUMMON THE BOSS');syncBreakoutBoss()};
 const oldTone=tone;tone=function(f,d,type,v,slide,delay){return oldTone(f,d,type,(Number(v)||.04)*(V70.settings.effectsVolume/100),slide,delay)};const oldNoise=noise;noise=function(d,v){return oldNoise(d,(Number(v)||.03)*(V70.settings.effectsVolume/100))};
 const oldFlip=sfxFlipper;sfxFlipper=function(){haptic(14);return oldFlip.apply(this,arguments)};const oldHit=sfxHit;sfxHit=function(k){haptic((Number(k)||1)>1.6?24:8);return oldHit.apply(this,arguments)};const oldBonus=sfxBonus;sfxBonus=function(){haptic([18,18,32]);return oldBonus.apply(this,arguments)};const oldDrain=sfxDrain;sfxDrain=function(){haptic([55,30,80]);return oldDrain.apply(this,arguments)};
 const oldMusic=hipHopStep;hipHopStep=function(step,t){oldMusic(step,t);if(combo>=2&&step%4===2)musicNoise(.018,.012*combo,t,6500);if(combo>=3&&step%8===0)musicTone(110*combo,.08,'triangle',.01*combo,t,20);if(combo>=4&&step%4===0)musicTone([261.63,293.66,329.63,392][(step/4)%4],.12,'sine',.012*combo,t,12);if(combo>=5&&totalXp()>=4500&&step%2===0)musicTone(523.25+(step%4)*65,.055,'square',.012,t,25);if(level===5&&!V70.bossDefeated&&step%4===0)musicTone(41.2,.25,'sawtooth',.045,t,-4)};
 const oldAdd=addScore;addScore=function(base,x,y){V70.maxCombo=Math.max(V70.maxCombo,combo);return oldAdd(V70.activePower==='triple'&&performance.now()<V70.powerEnds?base*3:base,x,y)};
 const oldCircle=circleHit;circleHit=function(o,boost,points){const hit=bumpers.includes(o)&&Math.hypot(ball.x-o.x,ball.y-o.y)<ball.r+o.r;if(hit)V70.bumperHits++;return oldCircle.apply(this,arguments)};
 V70.originalWinGame=winGame;winGame=function(){if(!V70.levelBossDefeated||!levelObjectivesMet()){setStatus('COMPLETE THE OBJECTIVES AND DEFEAT THE BOX BOSS TO WIN!');return}return V70.originalWinGame.apply(this,arguments)};
 const oldFinishBallTurn=finishBallTurn;finishBallTurn=async function(){if(!V70.mainDrainRegistered)registerBallLoss();const r=await oldFinishBallTurn.apply(this,arguments);V70.mainDrainRegistered=false;return r};
 const oldLose=loseBall;loseBall=function(){if(V70.ballSave){V70.ballSave=false;haptic([40,20,80]);showPowerToast('BALL SAVED!','THE SHIELD KEPT HOWIE IN THE GAME');resetBall();setStatus('BALL SAVE USED — HOLD LAUNCH');return}if(!V70.mainDrainRegistered){V70.mainDrainRegistered=true;registerBallLoss()}return oldLose.apply(this,arguments)};
 const oldUpdateExtraBalls=updateExtraBalls;updateExtraBalls=function(){const activeBefore=new Set(extraBalls.filter(b=>b.active).map(b=>b.id));const r=oldUpdateExtraBalls.apply(this,arguments);let drains=0;for(const id of activeBefore){const b=extraBalls.find(x=>x.id===id);if(b&&!b.active)drains++}for(let i=0;i<drains;i++)registerBallLoss();return r};
 const oldDrawWorld=drawWorld;drawWorld=function(){oldDrawWorld();drawPower();drawUnlockEffects();drawHowieFireworks();drawBreakoutBoss();drawBossAttackAndHowieHealth();drawHowieStars();drawBreakoutPoints();drawLargeHowieCounter();drawMegaCountdown()};const oldDraw=draw;draw=function(){oldDraw();drawReplayGhost();drawBossCornerHud()};
 const oldUpdate=updateReplaySystems;updateReplaySystems=function(){oldUpdate();captureReplayFrame();V70.maxCombo=Math.max(V70.maxCombo,combo);const total=document.getElementById('v73TotalPointsValue');if(total)total.textContent=Math.floor(score).toLocaleString();document.getElementById('bossHud').classList.remove('show');if(V70.dailyMode)updateDailyBadge();if(!V70.nextPowerAt)V70.nextPowerAt=performance.now()+18000;if(performance.now()>V70.nextPowerAt)spawnPower();checkPowerPickup();applyPowerPhysics();syncBreakoutBoss();updateBossAttack();if(autoPlay&&howieStarAttackReady())throwHowieStar();updateHowieStars();updateStarLaunchButton();updateLaunchPadRescue();triggerBoxLockGameOver();collideBreakoutBossFor(ball);for(const b of extraBalls)if(b.active)collideBreakoutBossFor(b)};
 const oldStart=startGame;startGame=function(){V70.runSubmitted=false;V70.bumperHits=0;V70.maxCombo=1;V70.lostBalls=0;V70.breakoutMultiplier=1;V70.breakoutShown=0;V70.breakoutBoss=false;V70.breakoutBossHp=1000000;V70.breakoutBossMax=1000000;V70.breakoutBossLastHit=0;V70.bossBattleStarted=false;V70.bossRetreatAt=0;V70.bossRegenLast=0;V70.howieBossHp=1000000;V70.bossAttackLast=0;V70.bossAttackUntil=0;V70.howieStars=[];V70.howieStarLast=0;V70.boxLockGameOver=false;V70.levelBossDefeated=false;V70.bossSequenceRunning=false;V70.mainDrainRegistered=false;V70.ballSave=false;V70.activePower=null;V70.power=null;V70.nextPowerAt=performance.now()+18000;resetBoss();const r=oldStart.apply(this,arguments);document.getElementById('bossHud').classList.remove('show');updateBreakoutLabel();document.getElementById('dailyModeBadge').hidden=!V70.dailyMode;setTimeout(startTutorial,500);return r};
 const oldAdvance=advanceLevel;advanceLevel=function(){V70.breakoutBoss=false;V70.breakoutBossHp=1000000;V70.bossBattleStarted=false;V70.bossRetreatAt=0;V70.bossRegenLast=0;V70.howieBossHp=1000000;V70.bossAttackLast=0;V70.bossAttackUntil=0;V70.levelBossDefeated=false;const next=level+1,r=oldAdvance.apply(this,arguments);setTimeout(()=>{nextFlapScore=(level-1)*LEVEL_GOAL+FLAP_GOAL*V70.breakoutMultiplier;setStatus('LEVEL '+level+' • EARN THE POINT GOAL AND FREE HOWIE TO SUMMON THE BOSS')},2850);return r};
 const oldFinish=finishRecord;finishRecord=async function(){savePersonalRun();renderPersonalBoards();if(V70.dailyMode){await submitDaily();return}try{const body={action:'finish',playerId,playerName,score:Math.floor(score),howieOutMs:Math.floor(outMs()),levelReached:level,bossDamage:V70.bossDamage};const res=await fetch(GAME_API,{method:'POST',headers:{Authorization:'Bearer '+GAME_ANON_KEY,apikey:GAME_ANON_KEY,'Content-Type':'application/json'},body:JSON.stringify(body)});if(!res.ok)throw new Error(String(res.status));const data=await res.json();const earned=Number(data.xpEarned)||0;V70.localXp+=earned;localStorage.setItem(XP_KEY,String(V70.localXp));showPowerToast('+'+earned+' XP','PLAYER PROGRESSION UPDATED');updateXpUi();await loadStats();await loadV70Data()}catch(e){return oldFinish.apply(this,arguments)}};
 const oldJackpot=awardSuperJackpot;awardSuperJackpot=function(){startInstantReplay('SUPER JACKPOT!');return oldJackpot.apply(this,arguments)};
 const oldLaunchAvailable=launchAvailable;launchAvailable=function(){return oldLaunchAvailable()||ballStuckOnLaunchPad()};const oldLaunch=launch;launch=function(p){const rescue=ballStuckOnLaunchPad();if(rescue){inShooter=true;drainCommitted=false;waiting=false}const r=oldLaunch.apply(this,arguments);if(rescue)setStatus('🚀 BALL RESCUED FROM THE LAUNCH PAD!');if(Number(p)>.98)setTimeout(()=>startInstantReplay('PERFECT LAUNCH!'),520);return r};
 document.getElementById('share').onclick=shareResultCard;document.getElementById('victoryShare').onclick=shareResultCard;document.getElementById('nativeShareBtn').onclick=nativeShareCard;document.getElementById('facebookShareBtn').onclick=facebookShare;
 const starButton=document.getElementById('launchBtn'),normalStarDown=starButton.onpointerdown;starButton.onpointerdown=function(e){if(howieStarAttackReady()){e.preventDefault();throwHowieStar();return}return normalStarDown.call(this,e)};starButton.addEventListener('pointerup',e=>{if(howieStarAttackReady()){e.preventDefault();e.stopImmediatePropagation()}},true);document.addEventListener('keydown',e=>{if(e.code==='Space'&&!e.repeat&&howieStarAttackReady()){e.preventDefault();e.stopImmediatePropagation();throwHowieStar()}},true);document.addEventListener('keyup',e=>{if(e.code==='Space'&&howieStarAttackReady()){e.preventDefault();e.stopImmediatePropagation()}},true);
 window.addEventListener('keydown',e=>{if(e.code==='Escape')V70.paused?closeSettings():openSettings()});
}
resetComputerDeviceStats();createUi();installHooks();syncSettingControls();loadV70Data();
})();
